// src/services/deploymentReadiness/deploymentBaseline.ts
// ─────────────────────────────────────────────────────────────────────────────
// Batch 330: the UI files that break the deployment-readiness rules today,
// recorded when the guard was added (see deploymentReadiness.guard.test.ts).
//
// These lists may only SHRINK. When you clean a file up, remove it here:
// the guard fails if a listed file no longer needs its entry, so the list
// can't go stale. A file not listed here may not break the rules at all.
//
// Paths are relative to src/.
// ─────────────────────────────────────────────────────────────────────────────

/** UI files that import a specific mock service (…/mockXxx) instead of the
 *  services index (`@/services`) or an injected dependency. */
export const MOCK_IMPORT_BASELINE: readonly string[] = [
  'components/AppShell/AppShell.tsx',
  'components/Audit/BreakGlassRebindModal.tsx',
  'components/Audit/InterfaceExceptionReviewModal.tsx',
  'components/Config/AI/resolveClientAiModel.ts',
  'components/Config/AI/resolveVoiceAiModel.ts',
  'components/Config/Actions/ActionsTab.tsx',
  'components/Config/Cytology/CytologyInstrumentationSection.tsx',
  'components/Config/Cytology/CytologyNomenclatureSettingsSection.tsx',
  'components/Config/Cytology/CytologyRegistrySettingsSection.tsx',
  'components/Config/Cytology/CytologyRoutingSettingsSection.tsx',
  'components/Config/Cytology/CytologyScreeningStrategySection.tsx',
  'components/Config/Cytology/CytologyWorkloadCapSettingsSection.tsx',
  'components/Config/Cytology/NonGynCytologyCategoriesSection.tsx',
  'components/Config/System/ActionGroupsSection.tsx',
  'components/Config/System/AssistLisPollingSection.tsx',
  'components/Config/System/BillingDictionarySection.tsx',
  'components/Config/System/BillingTypeTriggerSection.tsx',
  'components/Config/System/CancerRegistrySettingsSection.tsx',
  'components/Config/System/CaseMaskConfigSection.tsx',
  'components/Config/System/CassetteColorsSection.tsx',
  'components/Config/System/CassetteRoutingRulesSection.tsx',
  'components/Config/System/ConcordanceReviewSettingsSection.tsx',
  'components/Config/System/CytologyQcRulesSection.tsx',
  'components/Config/System/CytologyQcSettingsSection.tsx',
  'components/Config/System/CytotechCompetencyAssignmentsSection.tsx',
  'components/Config/System/DelegationTypeSection.tsx',
  'components/Config/System/DeliveryRulesSection.tsx',
  'components/Config/System/DepartmentsSection.tsx',
  'components/Config/System/DftExportPreviewSection.tsx',
  'components/Config/System/DisplayProfilesSection.tsx',
  'components/Config/System/DpVendorDictionarySection.tsx',
  'components/Config/System/ExternalResourcesSection.tsx',
  'components/Config/System/FppeAssignmentsSection.tsx',
  'components/Config/System/GrossImagingVendorDictionarySection.tsx',
  'components/Config/System/ImageManagementSystemVendorDictionarySection.tsx',
  'components/Config/System/JurisdictionPaymentMappingSection.tsx',
  'components/Config/System/MasterPaymentTypeDictionarySection.tsx',
  'components/Config/System/MigrationFieldMappingsSection.tsx',
  'components/Config/System/ModifierDictionarySection.tsx',
  'components/Config/System/NcciEditRulesSection.tsx',
  'components/Config/System/OrSuiteTerminalsSection.tsx',
  'components/Config/System/OutboundMessagePreviewSection.tsx',
  'components/Config/System/ParticipationTypesSection.tsx',
  'components/Config/System/PatientMatchReviewSection.tsx',
  'components/Config/System/PrintRoutingRuleSection.tsx',
  'components/Config/System/ReagentLotsSection.tsx',
  'components/Config/System/ReleaseBufferSection.tsx',
  'components/Config/System/ResearchFeedSection.tsx',
  'components/Config/System/RvuCodeMapSection.tsx',
  'components/Config/System/ScanStationsSection.tsx',
  'components/Config/System/SessionSecuritySection.tsx',
  'components/Config/System/SnomedCervicalHistologySeverityMappingSection.tsx',
  'components/Config/System/SpecimenCategoriesSection.tsx',
  'components/Config/System/StainDictionarySection.tsx',
  'components/Config/System/SubspecialtiesSection.tsx',
  'components/Config/System/WorkstationGroupsSection.tsx',
  'components/Config/System/WsiViewerVendorDictionarySection.tsx',
  'components/Contribution/aiContributionCalculations.ts',
  'components/GrossingHardware/CameraCaptureControl.tsx',
  'components/NavBar/NavBarScanStation.tsx',
  'components/PatientHistory/PatientHistoryModal.tsx',
  'components/QualityAssurance/PatientManagementSection.tsx',
  'components/QualityAssurance/QaScopeSwitcher.tsx',
  'components/RequestReview/RequestReviewModal.tsx',
  'components/ScanStationPrompt.tsx',
  'components/Search/CaseSearchBar.tsx',
  'components/TemplateBuilder/PartBuilderPage.tsx',
  'components/TemplateBuilder/PartLibraryTab.tsx',
  'components/TemplateBuilder/RoutingRulesTab.tsx',
  'components/TemplateBuilder/TemplateListTab.tsx',
  'components/ValidationStudies/ModelStoreModal.tsx',
  'components/ValidationStudies/ValidationStudiesSection.tsx',
  'components/Voice/SpeechConfigTab.tsx',
  'components/Voice/VoiceCommandOverlay.tsx',
  'components/Voice/VoiceMissPrompt.tsx',
  'components/Worklist/PoolClaimModal.tsx',
  'components/Worklist/WorklistTable.tsx',
  'contexts/VoiceProvider.tsx',
  'hooks/useDefaultActionOnScan.ts',
  'hooks/useDraftCache.ts',
  'hooks/useEnabledIdentifierFormats.ts',
  'hooks/useGlobalMaterialScanTracking.ts',
  'hooks/useGlobalStationSwitch.ts',
  'hooks/useIdleTimeout.ts',
  'main.tsx',
  'pages/AccessionPage/ClinicalHistory/ClinicalHistoryEntryPanel.tsx',
  'pages/AccessionPage/PatientLinkSearch.tsx',
  'pages/AddOnOrderPage/hooks/useAddOnOrderStation.ts',
  'pages/AuditLogPage.tsx',
  'pages/BatchManagement/DisposalQueuePage.tsx',
  'pages/BatchManagement/DisposalReportPage.tsx',
  'pages/BatchManagement/NewContainerModal.tsx',
  'pages/BatchManagement/PendingBatchQueuePage.tsx',
  'pages/ConfigurationPage.tsx',
  'pages/CriticalAlertAuditSection.tsx',
  'pages/CriticalAlertReferencePage/CriticalAlertReferencePage.tsx',
  'pages/CytologyQcQueuePage.tsx',
  'pages/CytologyWorklistPage/CytologyScreeningPage.tsx',
  'pages/CytologyWorklistPage/CytologyWorklistPage.tsx',
  'pages/CytologyWorklistPage/components/CytologySynopticFormView.tsx',
  'pages/EmbeddingStationPage/hooks/useEmbeddingStation.ts',
  'pages/FacilityOpsDashboard/FacilityOpsDashboardPage.tsx',
  'pages/FullReportPage.tsx',
  'pages/MicrotomyWorkstationPage/hooks/useMicrotomyWorkstation.ts',
  'pages/MigrationJobsPage.tsx',
  'pages/MockInterfaceEnginePage/MockInterfaceEnginePage.tsx',
  'pages/MolecularBatchManagement/MolecularBatchManagementPage.tsx',
  'pages/MolecularBatchPage/MolecularControlRulesPage.tsx',
  'pages/MolecularBatchPage/MolecularPlateBuilderPage.tsx',
  'pages/MolecularBatchPage/MolecularRackLoadingPage.tsx',
  'pages/MolecularBatchPage/MolecularRackWorklistPage.tsx',
  'pages/MolecularOrderQueuePage/MolecularOrderQueuePage.tsx',
  'pages/OutboundDispatchTrailSection.tsx',
  'pages/OutboundDlqSection.tsx',
  'pages/OutboundInterfaceDlqSection.tsx',
  'pages/PrintQueueDashboardSection.tsx',
  'pages/ReportPreview/ReportPreviewPage.tsx',
  'pages/SlideDistributionStationPage/hooks/useSlideDistributionStation.ts',
  'pages/SurgicalQaWorklistPage.tsx',
  'pages/Synoptic/useSynopticFlags.ts',
  'pages/SynopticReportPage/components/MaterialTreePanel.tsx',
  'pages/SynopticReportPage/components/ReleaseBufferBanner.tsx',
  'pages/SynopticReportPage/components/RightSynopticPanel.tsx',
  'pages/SynopticReportPage/components/WsiViewerLaunchButton.tsx',
  'pages/SynopticReportPage/hooks/checkStainQcGate.ts',
  'pages/SynopticReportPage/hooks/sharedHookTypes.ts',
  'pages/SynopticReportPage/hooks/useGrossingCompletion.ts',
  'pages/SynopticReportPage/hooks/useLisIntegration.ts',
  'pages/SynopticReportPage/hooks/useSignOutWorkflow.ts',
  'pages/SynopticReportPage/modals/MaterialTrackingHistoryModal.tsx',
  'pages/SynopticReportPage/modals/StainQcGateModal.tsx',
];

/** UI files that use localStorage/sessionStorage directly. Display
 *  preferences belong in utils/uiPreferences.ts; data belongs in a service. */
export const BROWSER_STORAGE_BASELINE: readonly string[] = [
  'components/AppShell/AppShell.tsx',
  'components/Common/InlineCommentThread.tsx',
  'components/Config/AI/aiProviderConfig.ts',
  'components/Config/AI/orchestratorModeConfig.ts',
  'components/Config/Protocols/protocolShared.tsx',
  'components/Config/System/DemoResetTab.auditTest.ts',
  'components/Config/System/RetentionSection.tsx',
  'components/Config/System/documentStyleConfig.ts',
  'components/Config/Templates/TemplateRenderer.tsx',
  'components/TemplateBuilder/TemplatePreviewPanel.tsx',
  'components/Worklist/PoolClaimModal.tsx',
  'components/Worklist/WorklistTable.tsx',
  'contexts/MessagingContext.tsx',
  'contexts/SystemConfigContext.tsx',
  'contexts/VoiceProvider.tsx',
  'hooks/useCompanionWindow.ts',
  'hooks/useCurrentDisplayProfile.ts',
  'hooks/useCurrentOrTerminal.ts',
  'hooks/useCurrentScanStation.ts',
  'hooks/useFootPedal.ts',
  'hooks/usePreviewChannel.ts',
  'pages/BillingLogsSection.tsx',
  'pages/ReportPreview/ReportPreviewPage.tsx',
  'pages/SynopticReportPage/hooks/useOrchestratorDraft.ts',
  'pages/WorklistPage/WorklistPage.tsx',
];

/** UI files that import the Firebase SDK directly instead of going through a
 *  service. */
export const FIREBASE_IMPORT_BASELINE: readonly string[] = [
  'hooks/usePendingEngineNotifications.ts',
];
