// src/services/clinical/ICriticalAlertDispatchService.ts
// ─────────────────────────────────────────────────────────────────────────────
// Real service for CriticalAlertDispatchRecord — the automated system's
// own append-only audit trail, distinct from (and additive to)
// ICriticalResultNotificationService's human-call log. Same real
// "never edit history, only add a new record" posture as every other
// audit-style service in this app.
// ─────────────────────────────────────────────────────────────────────────────

import type { ServiceResult } from '../types';
import type { CriticalAlertDispatchRecord } from '@/types/clinical/CriticalAlertDispatch';

export interface ICriticalAlertDispatchService {
  getByCaseId(caseId: string): Promise<ServiceResult<CriticalAlertDispatchRecord[]>>;

  /** Real, per direct guidance's own "Complete Audit Trail" ask
   *  (PS-136) — the full, cross-case dispatch history for the new
   *  internal, authenticated Critical Alerts audit viewer
   *  (CriticalAlertAuditSection.tsx). Same small-dataset,
   *  local-storage-scoped posture every other audit-style mock service
   *  in this app already accepts for a "list everything" query. */
  getAll(): Promise<ServiceResult<CriticalAlertDispatchRecord[]>>;

  /** Real, per direct guidance — records one automated dispatch
   *  attempt, including an honest, empty `channels` array when no
   *  automated channel could be resolved. Never partially recorded.
   *  `id` is optional and pre-generated by the caller only when a
   *  reference token (ICriticalAlertReferenceTokenService.ts) needs to
   *  link back to this exact record before it exists in storage —
   *  omit it to let this service generate one as before. */
  record(input: Omit<CriticalAlertDispatchRecord, 'id' | 'dispatchedAt'> & { id?: string }): Promise<ServiceResult<CriticalAlertDispatchRecord>>;
}
