// src/utils/detectIdentifierType.ts
// ─────────────────────────────────────────────────────────────────────────────
// Real, per direct guidance's own follow-up: "I also suspect a lot of
// business logic [in SearchPage.tsx]." Confirmed via direct
// investigation - detectIdentifierType/applyIdentifier were a real,
// nontrivial, multi-branch identifier-classification algorithm
// (slide barcode / MPI / accession / MRN / requisition / patient
// name / ambiguous, with real regex parsing against admin-
// configurable identifier formats) living entirely inside
// SearchPage.tsx itself, with zero test coverage (no SearchPage.test.tsx
// exists at all) - a real, concrete consequence of this logic sitting
// in the wrong layer, not just a stylistic preference.
//
// Extracted here verbatim - same real branches, same real order, same
// real fallback behavior - as a real, testable, standalone utility.
// detectIdentifierType stays pure. resolveIdentifierApplication
// deliberately does NOT call navigate() or setState itself (the
// original applyIdentifier did both) - it returns a real, structured
// result describing what the caller should do, so the actual
// side-effecting call sites (SearchPage.tsx) stay in the UI layer
// where they belong, while the real decision logic is fully testable
// in isolation.
// ─────────────────────────────────────────────────────────────────────────────

import { normalizeAccession, isAccession } from './normalizeAccession';
import type { IdentifierFormat } from '@/types/systemConfig';

export type IdentifierType = 'accession' | 'mrn' | 'mpi' | 'slide' | 'requisition' | 'name' | 'ambiguous' | null;

/** Real, per direct guidance - classifies a pasted/typed identifier
 *  string against the real, currently-enabled identifier formats.
 *  Same real branch order as the original: slide barcode (tier 1)
 *  first (triggers direct navigation), then MPI (this app's own
 *  internally-generated PID- prefix, never admin-configurable),
 *  then accession, then MRN, then requisition - each tested against
 *  every enabled format of that kind, not just one. Falls back to a
 *  real alpha-ratio heuristic for "name" vs "ambiguous" only when none
 *  of the configured formats match. */
export function detectIdentifierType(val: string, enabledFormats: IdentifierFormat[]): IdentifierType {
  if (!val.trim()) return null;
  const v = val.trim();
  try {
    // Slide barcodes first — trigger direct case navigation
    const slideMatch = enabledFormats.find(
      f => f.kind === 'slide' && f.enabled && f.tier === 1 &&
           new RegExp(f.pattern).test(v)
    );
    if (slideMatch) return 'slide';

    // Master Patient Index id — internally generated by this app
    // (services/patients/mockPatientIndexService.ts), always PID-
    // prefixed, so unlike MRN/accession/requisition this doesn't vary
    // by jurisdiction or external source system and doesn't need to
    // go through the admin-configurable IdentifierFormat system.
    if (/^PID-/i.test(v)) return 'mpi';

    // Accession number — tests every enabled accession format, not just one.
    const accessionFormats = enabledFormats.filter(f => f.kind === 'accession' && f.enabled);
    const accessionMatch = accessionFormats.find(f => isAccession(v, f.pattern));
    if (accessionMatch) return 'accession';

    // Patient identifier (MRN / NHS / CHI / IHI etc.) — same fix.
    const mrnFormats = enabledFormats.filter(f => f.kind === 'mrn' && f.enabled);
    if (mrnFormats.some(f => new RegExp(f.pattern).test(v))) return 'mrn';

    // Requisition number
    const reqMatch = enabledFormats.find(
      f => f.kind === 'requisition' && f.enabled && new RegExp(f.pattern).test(v)
    );
    if (reqMatch) return 'requisition';

  } catch { /* invalid regex — fall through */ }

  const alphaRatio = (v.match(/[a-zA-Z]/g)?.length ?? 0) / v.length;
  if (alphaRatio > 0.6) return 'name';
  if ((v.includes(' ') || v.includes(',')) && alphaRatio > 0.5) return 'name';
  return 'ambiguous';
}

export type IdentifierApplicationResult =
  | { action: 'navigate'; path: string }
  | { action: 'setFilters'; patientName: string; hospitalId: string; patientId: string; accessionNo: string };

/** Real, per direct guidance - resolves what a detected identifier
 *  type should actually do, as a real, structured, testable result -
 *  never a side effect itself. The original applyIdentifier's real
 *  behavior is fully preserved: a slide barcode with a real, real
 *  pipe-delimited ACC:/SPEC: payload (Epic Beaker etc.) navigates
 *  directly (with or without a specimen), a real 1D slide barcode
 *  extracts its own real accession prefix and navigates, and every
 *  other type resolves to the real, same filter fields the original
 *  always cleared-then-set. */
export function resolveIdentifierApplication(
  val: string,
  type: IdentifierType,
  enabledFormats: IdentifierFormat[],
  fallbackAccessionPattern: string
): IdentifierApplicationResult {
  if (type === 'slide') {
    // 2D pipe-delimited payload (Epic Beaker etc.)
    const pipeAcc = val.match(/ACC:([^|]+)/);
    if (pipeAcc) {
      const specMatch = val.match(/SPEC:([^|]+)/);
      return {
        action: 'navigate',
        path: specMatch ? `/case/${pipeAcc[1]}/synoptic?specimen=${specMatch[1]}` : `/case/${pipeAcc[1]}/synoptic`,
      };
    }
    // 1D slide — extract accession (e.g. S26-4200 from S26-4200-A1-1)
    const oneD = val.match(/^([A-Za-z]{1,3}\d{2}-\d{4,6})/i);
    if (oneD) return { action: 'navigate', path: `/case/${oneD[1]}/synoptic` };
    return { action: 'setFilters', patientName: '', hospitalId: '', patientId: '', accessionNo: val.trim() };
  }

  if (type === 'accession') {
    // Try each enabled accession format's own pattern for hyphen
    // normalization until one actually matches — a UK-shaped value
    // (SP26-4200, 1-2 letter prefix) won't normalize correctly against
    // the US-shaped default pattern's assumptions.
    const accessionFormats = enabledFormats.filter(f => f.kind === 'accession' && f.enabled);
    const normalized = accessionFormats
      .map(f => normalizeAccession(val.trim(), f.pattern))
      .find(n => accessionFormats.some(f => new RegExp(f.pattern, 'i').test(n)))
      ?? normalizeAccession(val.trim(), fallbackAccessionPattern);
    return { action: 'setFilters', patientName: '', hospitalId: '', patientId: '', accessionNo: normalized };
  }
  if (type === 'mrn')         return { action: 'setFilters', patientName: '', hospitalId: val.trim(), patientId: '', accessionNo: '' };
  if (type === 'mpi')         return { action: 'setFilters', patientName: '', hospitalId: '', patientId: val.trim(), accessionNo: '' };
  if (type === 'name')        return { action: 'setFilters', patientName: val.trim(), hospitalId: '', patientId: '', accessionNo: '' };
  if (type === 'requisition') return { action: 'setFilters', patientName: '', hospitalId: '', patientId: '', accessionNo: val.trim() };
  return { action: 'setFilters', patientName: val.trim(), hospitalId: val.trim(), patientId: '', accessionNo: val.trim() };
}
