// src/utils/grossingScreenOperations.ts
// ─────────────────────────────────────────────────────────────────────────────
// Real, per the Protocol-Driven Workflow Infrastructure story's Part
// 3 Grossing Screen. Pure, testable functions — same real reasoning
// as generateDefaultMaterial.ts's own extraction: genuinely worth
// verifying in isolation (confirmation-required removal, override
// logging, the Pending-only removal gate) without driving a real page
// component to do it. The caller (useGrossingScreen.ts) is
// responsible for persisting the returned Specimen via
// caseRouter.updateCase — these functions never touch case data
// themselves.
// ─────────────────────────────────────────────────────────────────────────────

import { getBlockLabel } from '@/utils/specimenLabeling';
import { cassetteIdentifier, slideIdentifier } from '@/types/labels/LabelData';
import type { HistologyBlock, Specimen, StainOrder, SpecimenGrossingOverride } from '@/types/case/Specimen';
import type { ProtocolPathway } from '@/services/protocols/IProtocolService';
import type { StainType } from '@/services/stains/IStainService';

export type GrossingOperationResult =
  | { ok: true; specimen: Specimen }
  | { ok: false; error: string }
  | { ok: false; needsConfirmation: true };

function genId(prefix: string): string {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
}

function logOverride(specimen: Specimen, entry: SpecimenGrossingOverride): SpecimenGrossingOverride[] {
  return [...(specimen.grossingOverrides ?? []), entry];
}

/**
 * Real, per the spec's own "Add Block → creates block with protocol
 * default stains (autoGenerated), piece count from defaultPieceCount."
 * `pathway` is the specific real ProtocolPathway to generate another
 * instance of — resolved/selected by the caller (a specimen with
 * several pathways needs a real, human choice of which one; a
 * single-pathway specimen has an obvious default). New block's own
 * stains are never userAdded — they came straight from the protocol,
 * same as every block generateDefaultMaterial.ts itself produces.
 */
export function addGrossingBlock(
  specimen: Specimen,
  pathway: ProtocolPathway,
  fullAccession: string,
  specimenLabelStyle?: 'alpha-specimen' | 'numeric-specimen',
): GrossingOperationResult {
  const existingBlocks = specimen.blocks ?? [];
  const blockLabel = getBlockLabel(existingBlocks.length, specimenLabelStyle);
  const sortedTasks = [...pathway.tasks].sort((a, b) => a.stepOrder - b.stepOrder);
  const stains: StainOrder[] = [];
  sortedTasks.forEach((task) => {
    task.stainTypeIds.forEach(() => {
      stains.push({
        id: genId('stain'),
        stainName: task.action,
        status: 'Pending Cut',
        displayId: slideIdentifier(fullAccession, specimen.label, blockLabel, `L${stains.length + 1}`),
      });
    });
  });
  const newBlock: HistologyBlock = {
    id: genId('block'),
    label: blockLabel,
    status: 'Pending',
    stains,
    sourcePathwayName: pathway.pathwayName,
    fixativeType: pathway.fixativeType,
    processingFormat: pathway.processingFormat,
    requiresDecal: pathway.requiresDecal,
    displayId: cassetteIdentifier(fullAccession, specimen.label, blockLabel),
    pieceCount: pathway.defaultPieceCount,
  };
  return { ok: true, specimen: { ...specimen, blocks: [...existingBlocks, newBlock] } };
}

/** Real, per the spec's own "Remove Block → permitted only in Pending
 *  status; blocked with explanation once processing has begun." */
export function removeGrossingBlock(specimen: Specimen, blockId: string): GrossingOperationResult {
  const block = (specimen.blocks ?? []).find(b => b.id === blockId);
  if (!block) return { ok: false, error: 'Block not found.' };
  if (block.status !== 'Pending') {
    return { ok: false, error: `Block ${specimen.label}${block.label} cannot be removed — it is already "${block.status}" and processing has begun.` };
  }
  return { ok: true, specimen: { ...specimen, blocks: (specimen.blocks ?? []).filter(b => b.id !== blockId) } };
}

/** Real, per the spec's own "Add Stain → dropdown filtered to
 *  allowedAdditionalStainTypeIds; stain flagged userAdded; block
 *  flagged userModified." Filtering against allowedAdditionalStainTypeIds
 *  is the caller's own job (the dropdown itself) — this function
 *  trusts the stainType it's given, same real "the UI already
 *  constrained the choice" posture as every other real form submit in
 *  this app. */
export function addGrossingStain(
  specimen: Specimen,
  blockId: string,
  stainType: StainType,
  actor: string,
  fullAccession: string,
): GrossingOperationResult {
  const block = (specimen.blocks ?? []).find(b => b.id === blockId);
  if (!block) return { ok: false, error: 'Block not found.' };
  const newStain: StainOrder = {
    id: genId('stain'),
    stainName: stainType.name,
    status: 'Pending Cut',
    displayId: slideIdentifier(fullAccession, specimen.label, block.label, `L${block.stains.length + 1}`),
    userAdded: true,
  };
  const updatedBlocks = (specimen.blocks ?? []).map(b =>
    b.id !== blockId ? b : { ...b, stains: [...b.stains, newStain], userModified: true }
  );
  const overrideEntry: SpecimenGrossingOverride = {
    field: 'stainAdded', blockLabel: block.label,
    originalValue: '(none)', newValue: stainType.name,
    actor, timestamp: new Date().toISOString(),
  };
  return { ok: true, specimen: { ...specimen, blocks: updatedBlocks, grossingOverrides: logOverride(specimen, overrideEntry) } };
}

/** Real, per the spec's own "Remove Stain → confirmation prompt if
 *  removing a protocol default; logged as override." Removing a
 *  stain the tech themselves just added (userAdded: true) is simply
 *  undoing their own addition — no confirmation, no audit entry,
 *  same real reasoning as never logging an override for something
 *  that was never the protocol's own default in the first place.
 *  Pass `confirmed: true` only after the caller's own real
 *  confirmation prompt has been answered — this function never shows
 *  UI itself. */
export function removeGrossingStain(
  specimen: Specimen,
  blockId: string,
  stainId: string,
  actor: string,
  confirmed: boolean,
): GrossingOperationResult {
  const block = (specimen.blocks ?? []).find(b => b.id === blockId);
  if (!block) return { ok: false, error: 'Block not found.' };
  const stain = block.stains.find(s => s.id === stainId);
  if (!stain) return { ok: false, error: 'Stain not found.' };

  const isProtocolDefault = !stain.userAdded;
  if (isProtocolDefault && !confirmed) {
    return { ok: false, needsConfirmation: true };
  }

  const updatedBlocks = (specimen.blocks ?? []).map(b =>
    b.id !== blockId ? b : { ...b, stains: b.stains.filter(s => s.id !== stainId), userModified: isProtocolDefault ? true : b.userModified }
  );
  const grossingOverrides = isProtocolDefault
    ? logOverride(specimen, { field: 'stainRemoved', blockLabel: block.label, originalValue: stain.stainName, newValue: '(removed)', actor, timestamp: new Date().toISOString() })
    : specimen.grossingOverrides;
  return { ok: true, specimen: { ...specimen, blocks: updatedBlocks, grossingOverrides } };
}

/** Real, per the spec's own "Piece count → pre-populated, editable...
 *  changes logged." Always logged — unlike stain removal, there's no
 *  real "this was already my own addition" exemption for a numeric
 *  field every block has from the start. */
export function updateGrossingPieceCount(
  specimen: Specimen,
  blockId: string,
  newCount: number,
  actor: string,
): GrossingOperationResult {
  const block = (specimen.blocks ?? []).find(b => b.id === blockId);
  if (!block) return { ok: false, error: 'Block not found.' };
  const originalValue = block.pieceCount != null ? String(block.pieceCount) : '(none)';
  const updatedBlocks = (specimen.blocks ?? []).map(b => b.id !== blockId ? b : { ...b, pieceCount: newCount });
  const overrideEntry: SpecimenGrossingOverride = {
    field: 'pieceCount', blockLabel: block.label,
    originalValue, newValue: String(newCount),
    actor, timestamp: new Date().toISOString(),
  };
  return { ok: true, specimen: { ...specimen, blocks: updatedBlocks, grossingOverrides: logOverride(specimen, overrideEntry) } };
}
